name: Document package 
on:
    push:
        branches: [main, feature/update_docs]
jobs:
    update_cli_doc:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10" # install the python version needed
            - name: Document CLI and write to folder
              run: |
                    make deps-install
                    mkdir -p docs
                    poetry run typer postprocessing_variant_calls.main utils docs > docs/cli.md
                    cp README.md docs/README.md
            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: "add doc for cli"
                add: '["docs/*.md --force"]'
            - uses: actions/checkout@v4
              with:
                ref: docs
            - uses: jaywcjlove/github-action-read-file@main
              id: cli
              with:
                branch: ${{ github.ref }}
                path: docs/cli.md
            - uses: jaywcjlove/github-action-read-file@main
              id: readme
              with:
                branch: ${{ github.ref }}
                path: docs/README.md
            - name: Write Docs
              id: write_yml_module
              if: ${{ steps.cli.outputs.size == '' }}
              run: echo '${{ steps.cli.outputs.content }}' > ${{ github.workspace }}/cli.md
            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: "add doc for cli"
                add: '["*.md --force"]'
                push: 'origin docs --set-upstream --force'
