name: Document package 
on:
    push:
        branches: [feature/sync_docs]
jobs:
    update_cli_doc:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10" # install the python version needed
            - name: Document CLI and write to folder
              run: |
                    make deps-install
                    mkdir temp
                    poetry run typer postprocessing_variant_calls.main utils docs > temp/CLI.md
            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: "add doc for CLI"
                add: '["temp/*.md --force"]'
                push: 'origin docs --force'
