name: Document package 
on:
    push:
        branches: [feature/sync_docs]
jobs:
    update_cli_doc:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PAT }}
            - name: Set up Python 
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Document CLI and write to folder
              run: |
                    make deps-install
                    poetry run typer postprocessing_variant_calls.main utils docs > docs/CLI.md
            - uses: actions/checkout@v4
              with:
                ref: docs
            - uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actions
                message: "add doc for CLI"
                add: '["docs/*.md --force", "SUMMARY.md --force"]'
                cwd: "./"
