name: Document package 
on:
    push:
        branches: [main, develop]
jobs:
    update_cli_doc:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.PAT }}
            - name: Set up Python 
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Check for changes
              id: git_changes
              run: echo "HAS_CHANGES=$(if git diff --quiet; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_ENV
                # Debug output
            - name: Debug HAS_CHANGES
              run: echo $HAS_CHANGES
              
            - name: Document CLI and write to folder
              if: env.HAS_CHANGES == 'true'
              run: |
                    make deps-install
                    poetry run typer postprocessing_variant_calls.main utils docs > docs/CLI.md
                    rm docs/README.md
                    cp README.md docs/README.md
                    git config --global user.name 'buehlere'
                    git config --global user.email 'buehlere77@gmail.com'
                    git add ./docs
                    git commit -m "Updating the repository GitHub MD documentation in the docs folder"
                    git push -f origin           
