name: Document package 
on:
    push:
        branches: "feature/docs_cleanup" #[main, develop, release/*]
    pull_request:
        branches: "*"
jobs:
    run_test_vardict_filter:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Document and write to folder
              run: |
                  make deps-install
                  poetry run typer postprocessing_variant_calls.main utils docs > docs/CLI.md
            - name: Commit and Push Docs
              run: |
                    git config --local user.name "buehlere"
                    git add ./docs
                    git commit -m "Updating the repository GitHub MD documentation in the docs folder"
                    git push



