name: Document package 
on:
    push:
        branches: [main, feature/mafbymaf] #[main, develop, release/*]
jobs:
    run_test_vardict_filter:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Document CLI and write to folder
              run: |
                    make deps-install
                    poetry run typer postprocessing_variant_calls.main utils docs > CLI.md
            - name: Commit and Push Docs
              run: |
                    git config --local user.name "buehlere"
                    git config --global user.email "buehlere77@gmail.com"
                    git add CLI.md
                    git commit -m "Updating the repository GitHub CLI documentation"
                    git push origin origin/docs
