name: publish_conda

on:
    push:
        branches: [feature/conda]
        tags:
            - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
